[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending_dapp = "C1kXjvQ96YVqyvkBF6cF9W28YmieevsA37WNZ8uKfWXF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster_dev = "https://api.devnet.solana.com"
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"
[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"
program = "pyth"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
